webStackDev:
  name: webStackDev #if you change this, run cdktf destroy on this stack first! "keep less than 24 characters in length, must match pattern [_A-Za-z][_0-9A-Za-z]*
  subdomainName: dev #lowercase only
  appsyncDomainName: apidev.s6pack.build
  s3WebsiteDomainName: dev.s6pack.build
  sfn:
    logLevel: ALL
    includeExecutionData: true
  appsync:
    authenticationType: AMAZON_COGNITO_USER_POOLS
    additionalAuthenticationType: AWS_IAM
    defaultAction: ALLOW
webStackBlue:
  name: webStackBlue #if you change this, run cdktf destroy on this stack first! "keep less than 24 characters in length, must match pattern [_A-Za-z][_0-9A-Za-z]*
  subdomainName: blue #lowercase only
  appsyncDomainName: apiblue.s6pack.build
  s3WebsiteDomainName: blue.s6pack.build
  sfn:
    logLevel: ALL
    includeExecutionData: true
  appsync:
    authenticationType: AMAZON_COGNITO_USER_POOLS
    additionalAuthenticationType: AWS_IAM
    defaultAction: ALLOW
webStackGreen:
  name: webStackGreen #if you change this, run cdktf destroy on this stack first! "keep less than 24 characters in length, must match pattern [_A-Za-z][_0-9A-Za-z]*
  subdomainName: green #lowercase only
  appsyncDomainName: apigreen.s6pack.build
  s3WebsiteDomainName: green.s6pack.build
  sfn:
    logLevel: ALL
    includeExecutionData: true
  appsync:
    authenticationType: AMAZON_COGNITO_USER_POOLS
    additionalAuthenticationType: AWS_IAM
    defaultAction: ALLOW
